#+TITLE: My emacs doom configuration
#+AUTHOR: Huy Le
#+EMAIL: dacrazyazn.com
#+LANGUAGE: en
#+STARTUP: inlineimages
#+PROPERTY: header-args :tangle yes :cache yes :results silent :padline no


* Table of Contents :TOC_3_gh:
- [[#original-repo][Original Repo]]
  - [[#personal-notes][Personal notes]]
  - [[#resources][Resources]]
    - [[#nmartin84-github--good-for-literate-programming][nmartin84 Github :: good for literate programming]]
    - [[#literate-doom-emacs-config--blog-post-using-org-literate-programming][Literate doom emacs config :: blog post using org literate programming]]
- [[#configuration][Configuration]]
  - [[#personal-information][Personal Information]]
    - [[#set-full-name][Set full name]]
    - [[#set-email-address][Set email address]]
  - [[#doom-core][Doom core]]
    - [[#emacsserver][EmacsServer]]
    - [[#core][Core]]
    - [[#keybinds][Keybinds]]
    - [[#os][Os]]
    - [[#scratch][Scratch]]
    - [[#ui][Ui]]
  - [[#doom-modules][Doom modules]]
    - [[#orgmode][Orgmode]]
    - [[#centaur-tabs][Centaur Tabs]]
    - [[#custom-drag-and-drop-function][Custom drag and drop function]]
    - [[#custom-copy-and-paste-images][Custom copy and paste images]]
    - [[#doom-modeline][Doom-modeline]]
- [[#load-custom-bindings][Load custom bindings]]

* [[https://github.com/Brettm12345/doom-emacs-literate-config][Original Repo]]
To get more configurations get it from here. This is really good, allows me to annotate all my changes to the default DOOM configuration

** Personal notes
Things to keep in mind
+ run ~.emacs.d/bin/doom sync~ to get things rebuilt
  + would ~M-x doom/reload~ work? have yet to try

** Resources
*** [[https://github.com/nmartin84/.doom.d][nmartin84 Github]] :: good for literate programming
*** TODO [[https://dotdoom.rgoswami.me/config.html][Literate doom emacs config]] :: blog post using org literate programming
  Really good resource, start checking out localleader stuff here

* Configuration
** Personal Information
*** Set full name
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Huy Le")
#+END_SRC
*** Set email address
#+BEGIN_SRC emacs-lisp
(setq user-mail-address "dacrazyazn.com")
#+END_SRC
** Doom core

Here I setup my config for the =doom-emacs= [[doom:core/][core]]
*** EmacsServer

#+BEGIN_SRC emacs-lisp
;; (load "server")
;; (unless (server-running-p) (server-start))
#+END_SRC

*** [[doom:core/core.el][Core]]
**** Do not create lockfiles for files being edited
#+BEGIN_SRC emacs-lisp
(setq create-lockfiles nil)
#+END_SRC
*** [[doom:core/core-keybinds.el][Keybinds]]
Here I set my keybinds these are applied on top of the [[doom-modules:config/default/+emacs-bindings.el][defaults]]
**** Global keybinds
**** DONE Localleader
+ Default ~localleader~ is ~SPC-m~
+ see if we can get this updated to ~;~

#+BEGIN_SRC emacs-lisp
(setq doom-localleader-key ";")
(setq doom-localleader-alt-key "M-;")
#+END_SRC
**** Leader keybinds
#+BEGIN_SRC emacs-lisp
(map! :leader
      (:prefix "TAB"
        :desc "Rename workspace"       "r"  #'+workspace/rename)
      (:prefix "f"
        :desc "Find remote file"      "R" #'counsel-tramp
        :desc "Find file in dotfiles" "t" #'+brett/find-in-dotfiles
        :desc "Browse dotfiles"       "T" #'+brett/browse-dotfiles)
      (:prefix "n"
        :desc "Browse mode notes"    "m" #'+brett/find-notes-for-major-mode
        :desc "Browse project notes" "p" #'+brett/find-notes-for-project)
      (:prefix "t"
        :desc "Rainbow mode" "r" #'rainbow-mode))
#+END_SRC
**** Use ~] SPC~ and ~[ SPC~ to insert newlines above and below
 Similar to [[github:tpope/vim-unimpaired][vim-unimpaired]]
#+BEGIN_SRC emacs-lisp
(map!
 (:after evil
   :m  "] SPC" #'evil-motion-insert-newline-below
   :m  "[ SPC" #'evil-motion-insert-newline-above))
#+END_SRC
**** Easy window navigation
#+BEGIN_SRC emacs-lisp
;; (map!
;;  (:after evil
;;    :en "C-h"   #'evil-window-left
;;    :en "C-j"   #'evil-window-down
;;    :en "C-k"   #'evil-window-up
;;    :en "C-l"   #'evil-window-right))
#+END_SRC

#+BEGIN_SRC emacs-lisp
;; Many thanks to the author of and contributors to the following posts:
;; https://gist.github.com/mislav/5189704
;; https://robots.thoughtbot.com/post/53022241323/seamlessly-navigate-vim-and-tmux-splits
;;
;; TODO: Make a script that generates tmux and emacs code without duplication
;;
;; NOTE: My keybindings are not the default emacs ones, using windmove

;; Try to move direction, which is supplied as arg
;; If cannot move that direction, send a tmux command to do appropriate move
;; (defun windmove-emacs-or-tmux(dir tmux-cmd)
;; (interactive)
;; (if (ignore-errors (funcall (intern (concat "windmove-" dir))))
;; nil                       ;; Moving within emacs
;; (shell-command tmux-cmd)) ;; At edges, send command to tmux
;; )

;; ;Move between windows with custom keybindings
;; (global-set-key (kbd "C-k")
;;    '(lambda () (interactive) (windmove-emacs-or-tmux "up"  "tmux select-pane -U")))
;; (global-set-key (kbd "C-j")
;;    '(lambda () (interactive) (windmove-emacs-or-tmux "down"  "tmux select-pane -D")))
;; (global-set-key (kbd "C-l")
;;    '(lambda () (interactive) (windmove-emacs-or-tmux "right" "tmux select-pane -R")))
;; (global-set-key (kbd "C-h")
;;    '(lambda () (interactive) (windmove-emacs-or-tmux "left"  "tmux select-pane -L")))
#+END_SRC
**** Org Mode
#+BEGIN_SRC emacs-lisp
;; (map! (:localleader
;;         (:after evil-org
;;           :map evil-org-mode-map
;;           "/" #'counsel-org-goto)))
#+END_SRC
**** Dired
#+BEGIN_SRC emacs-lisp
;; (map!
;;  (:after dired
;;     (:map dired-mode-map
;;     "C-SPC" #'peep-dired)))
#+END_SRC
**** Splitting Buffers
This would be used when looking at a list
and doing ~C-o s~ for horizontal split
#+BEGIN_SRC emacs-lisp
;; (after! ivy
;;   (ivy-set-actions
;;    'ivy-switch-buffer
;;    '(("s" evil-window-split "split horizontally")
;;      ("v" evil-window-vsplit "split vertically")))
;;   (ivy-set-actions
;;    'counsel-find-file
;;    '(("s" evil-window-split "split horizontally")
;;      ("v" evil-window-vsplit "split vertically"))))
#+END_SRC
**** Treemacs
Allow ~C-h~ and ~C-l~ to switch buffers
#+BEGIN_SRC emacs-lisp
;; (map!
;;  (:after treemacs-evil
;;    (:map evil-treemacs-state-map
;;      "C-h" #'evil-window-left
;;      "C-l" #'evil-window-right)))
#+END_SRC
**** Buffer Handling
***** TODO close the current buffer with 'q'
+ want to be able to manulate buffer similar to Vim
+ This will probably taking some diggin because ~:q~ is tied o EVIL mode?
  try looking up ~evil-delete-window~
  or just ~delete-window~ in general
+ in Emacs this feature is ~C-x, 0~ to delete the current window
  to delete the other window it would be ~C-x, 1~


#+BEGIN_SRC emacs-lisp
;; (setq doom-localleader-key ";")
#+END_SRC
**** Show keybind help with less of a delay
#+BEGIN_SRC emacs-lisp
(after! which-key
  (setq which-key-idle-delay 0.5
        which-key-idle-secondary-delay 0.01
        which-key-sort-order 'which-key-key-order-alpha))
#+END_SRC

*** [[doom:core/core-os.el][Os]]
**** Mouse wheel
#+BEGIN_SRC emacs-lisp
(setq mouse-wheel-scroll-amount '(3)
      mouse-wheel-progressive-speed t
      mouse-wheel-follow-mouse t
      scroll-step 1)
#+END_SRC
*** [[doom:core/autoload/scratch.el][Scratch]]
**** Make scratchpad buffers inherit the major mode of the current buffer
#+BEGIN_SRC emacs-lisp
(setq doom-scratch-buffer-major-mode t)
#+END_SRC
*** [[doom:core/core-ui.el][Ui]]
**** Highlight trailing whitespace
#+BEGIN_SRC emacs-lisp
(setq show-trailing-whitespace t)
#+END_SRC
**** Set the scale factor for ~all-the-icons~
#+BEGIN_SRC emacs-lisp
(after! all-the-icons
  (setq all-the-icons-scale-factor 1.0))
#+END_SRC
**** Immediately show eldoc
#+BEGIN_SRC emacs-lisp
;; (setq eldoc-idle-delay 0)
#+END_SRC
**** Enable relative line number
#+BEGIN_SRC emacs-lisp
(setq doom-line-numbers-style 'relative)
#+END_SRC
** Doom modules
Here I make customization to all the modules I have enabled in doom. Each of the headers is a link to their respective module
*** Orgmode
here everything for org should be in ~~/docs/org~ folder
+ setting the agenda files, allow orgmode to scan through to create agenda

#+BEGIN_SRC emacs-lisp
(use-package! org
  :config
  (setq org-agenda-files (file-expand-wildcards "~/docs/org/*.org"))
  (setq org-directory (expand-file-name "~/docs/org"))
  (setq org-cycle-separator-lines 1)
  (defvar +org-dir (expand-file-name "~/docs/org")))

#+END_SRC
**** Org-Capture
Capture things quickly - [[https://emacsnyc.org/assets/documents/how-i-use-org-capture-and-stuff.pdf][good article to help]]

#+BEGIN_SRC emacs-lisp
(use-package! org
  :config
  (setq org-capture-templates
        '(("l" "Linked Tasks" entry (file+headline "~/docs/org/gtd.org" "Linked Tasks")
           "* TODO %?\n  Entered on: %U - %a\n")
          ("t" "Tasks" entry (file+headline "~/docs/org/gtd.org" "Tasks")
           "* TODO %?\n  Entered on: %U\n")
          ("p" "Private" entry (file+datetree "~/docs/org/logbook.org")
           "* %?\n\n")
          ("j" "Journal" entry (file+datetree "~/docs/org/journal.org")
           "* %?\n\n"))))
#+END_SRC

**** Org-Download

there is ~org-attach-directory~ and ~org-download-image-dir~

***** Setting attachment method
the ~attach~ method is used to keep the data structure consistent with org-mode attachment system

#+BEGIN_SRC emacs-lisp
;; (setq org-attach-directory $HOME/testing/attachment)
(setq org-download-method 'attach)
#+END_SRC

***** DONE ChromeOS clipbaord setting for screenshot
need to get this fix for MacOS since the same ~xclip~ clipboard is not being used

#+BEGIN_SRC emacs-lisp
;; (setq org-attach-directory $HOME/testing/attachment)
;; (setq org-download-screenshot-method "xclip -selection clipboard -t image/png -o > %s")

(after! org
  (setq org-download-screenshot-method "pngpaste %s"))
#+END_SRC
***** TODO [#A] MacOS Clipboard setting for screenshot

**** Org-Journal


#+BEGIN_SRC emacs-lisp
(after! org
  (setq org-journal-file-type 'weekly))
#+END_SRC

**** Org-Agenda

#+BEGIN_SRC emacs-lisp
(after! org
  (setq org-agenda-custom-commands
      '(("%" "Appointments" agenda* "Today's appointments"
	 ((org-agenda-span 1)
          (org-agenda-max-entries 3))))))
#+END_SRC


*** Centaur Tabs

#+BEGIN_SRC emacs-lisp
(setq centaur-tabs-height 25)
(setq centaur-tabs-cycle-scope 'tabs)
#+END_SRC

*** Custom drag and drop function
#+BEGIN_SRC emacs-lisp
;; (defun my-dnd-func (event)
;;   (interactive "e")
;;   (goto-char (nth 1 (event-start event)))
;;   (x-focus-frame nil)
;;   (let* ((payload (car (last event)))
;;          (type (car payload))
;;          (fname (cadr payload))
;;          (img-regexp "\\(png\\|jp[e]?g\\)\\>"))
;;     (cond
;;      ;; insert image link
;;      ((and  (eq 'drag-n-drop (car event))
;;             (eq 'file type)
;;             (string-match img-regexp fname))
;;       (insert (format "[[%s]]" fname))
;;       (org-display-inline-images t t))
;;      ;; insert image link with caption
;;      ((and  (eq 'C-drag-n-drop (car event))
;;             (eq 'file type)
;;             (string-match img-regexp fname))
;;       (insert "#+ATTR_ORG: :width 300\n")
;;       (insert (concat  "#+CAPTION: " (read-input "Caption: ") "\n"))
;;       (insert (format "[[%s]]" fname))
;;       (org-display-inline-images t t))
;;      ;; C-drag-n-drop to open a file
;;      ((and  (eq 'C-drag-n-drop (car event))
;;             (eq 'file type))
;;       (find-file fname))
;;      ((and (eq 'M-drag-n-drop (car event))
;;            (eq 'file type))
;;       (insert (format "[[attachfile:%s]]" fname)))
;;      ;; regular drag and drop on file
;;      ((eq 'file type)
;;       (insert (format "[[%s]]\n" fname)))
;;      (t
;;       (error "I am not equipped for dnd on %s" payload)))))


;; (define-key org-mode-map (kbd "<drag-n-drop>") 'my-dnd-func)
;; (define-key org-mode-map (kbd "<C-drag-n-drop>") 'my-dnd-func)
;; (define-key org-mode-map (kbd "<M-drag-n-drop>") 'my-dnd-func)
#+END_SRC

**** Getting it to work on macos

should work as normal on windows, this is needed for macos
#+BEGIN_SRC emacs-lisp
(global-set-key [M-s-drag-n-drop] 'ns-drag-n-drop-as-text)
#+END_SRC

*** Custom copy and paste images

#+BEGIN_SRC emacs-lisp
;; (defun org-insert-clipboard-image (&optional file)
;;   (interactive "F")
;;   (shell-command (concat "pngpaste " file))
;;   (insert (concat "[[" file "]]"))
;;   (org-display-inline-images))

;; (defun my/org-insert-clipboard ()
;;     (interactive)
;;     (setq myvar/folder-path (concat default-directory "img/")) ;make the img directory
;;     (if (not (file-exists-p myvar/folder-path))
;;         (mkdir myvar/folder-path)) ;create the directory if it doesn't exist
;;     (let* ((image-file (concat
;;                         myvar/folder-path
;;                         (buffer-name)
;;                         "_"
;;                         (format-time-string "%Y%m%d_%H%M%S_.png")))
;;            (exit-status
;;             (call-process "convert" nil nil nil
;;                           "clipboard:" image-file)))
;;       (org-insert-link nil (concat "file:" image-file) "")
;;       (org-display-inline-images)))


(defun org-insert-image ()
  (interactive)
  (let* ((path (concat default-directory "data/"))
         (image-file (concat
                      path
                      (buffer-name)
                      (format-time-string "_%Y%m%d_%H%M%S.png"))))
    (if (not (file-exists-p path))
        (mkdir path))
    (shell-command (concat "pngpaste " image-file))
    (org-insert-link nil (concat "file:" image-file) ""))
    ;; (org-display-inline-images) ;; show inline picture
  )
#+END_SRC

*** Doom-modeline
change mode line so we can see projects!
#+BEGIN_SRC emacs-lisp
;; (setq doom-modeline-def-modeline "project")

;; (use-package doom-modeline
;;   :ensure t
;;   :init (doom-modeline-mode 1)
;;   )
;; (with-eval-after-load "doom-modeline"
;;   (doom-modeline-def-modeline 'main
;;   '(misc-info bar workspace-name window-number modals matches buffer-info remote-host buffer-position word-count parrot selection-info)
;;   '(objed-state persp-name battery grip irc mu4e gnus github debug lsp minor-modes input-method indent-info buffer-encoding major-mode process vcs checker)
;;   )
;; )
  ;; Define your custom doom-modeline
;; (doom-modeline-def-modeline 'my-simple-line
;;     '(bar " " buffer-info)
;;     '(misc-info))

;; ;; Add to `doom-modeline-mode-hook` or other hooks
;; (defun setup-custom-doom-modeline ()
;;     (doom-modeline-set-modeline 'my-simple-line 'default))
;; (add-hook 'doom-modeline-mode-hook 'setup-custom-doom-modeline)
#+END_SRC
* Load custom bindings

#+BEGIN_SRC emacs-lisp
(load! "+bindings")
#+END_SRC
